# Generated by Django 2.2.19 on 2022-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220209_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Аутентифицированный юзер'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=78, verbose_name='статус'),
        ),
    ]
