# Generated by Django 3.2.12 on 2022-04-03 17:15

import django.core.validators
import reviews.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220209_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(reviews.models.current_year, 'The time machine has not been invented yet.'), django.core.validators.MinValueValidator(1895, 'Start at 1895 - year of invention of cinema.')], verbose_name='release year'),
        ),
    ]
